//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HyosungMotor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BannerTranslations
    {
        public int Id { get; set; }
        public int LanguageId { get; set; }
        public int BannerId { get; set; }
        public string Heading { get; set; }
        public string SubHeading { get; set; }
        public string Description { get; set; }
    
        public virtual Banners Banners { get; set; }
        public virtual Languages Languages { get; set; }
    }
}
