//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HyosungMotor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SysCategoryValues
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> DictionaryId { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public Nullable<int> ParentId { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.DateTime> DateDeleted { get; set; }
        public string UserDeleted { get; set; }
        public string UserCreated { get; set; }
        public System.DateTime DateCreated { get; set; }
        public string UserModified { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public int Status { get; set; }
        public int SortOrder { get; set; }
    
        public virtual SysCategories SysCategories { get; set; }
        public virtual SysDictionnary SysDictionnary { get; set; }
    }
}
