//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HyosungMotor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SysMenus
    {
        public string Id { get; set; }
        public string Name { get; set; }
        public string URL { get; set; }
        public string ParentId { get; set; }
        public string IconCss { get; set; }
        public int SortOrder { get; set; }
        public int Status { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.Guid UserCreated { get; set; }
        public Nullable<System.DateTime> DateDeleted { get; set; }
        public Nullable<System.Guid> UserDeleted { get; set; }
        public Nullable<System.Guid> UserModified { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public bool IsDeleted { get; set; }
    }
}
