//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HyosungMotor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SysRoleMapping
    {
        public int Id { get; set; }
        public string RoleId { get; set; }
        public string ControllerId { get; set; }
        public string ActionId { get; set; }
        public string ActionName { get; set; }
        public bool IsAllow { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string CreateUid { get; set; }
    
        public virtual SysRoles SysRoles { get; set; }
    }
}
